fix: scalar types should not have a chevron icon indicating you can expand it
asyncapi/html-template pull request #99
Opened 2020-10-14 15:03 UTC by gabrielclaudino

**Description**

The scalar types are coming with an empty object in `patternProperties()` thus triggering the `isExpandable` filter. I changed the condition to verify if the object returned by `patternProperties()` is empty or not. It may be valid to also check why they are coming with it in the first place.

**Related issue**
Resolves #50

2020-10-15 09:54 UTC, derberg requested changes
This one was a tricky beast 😄 
Please also adjust the tests. As you can see they were passing no matter what change you did, even though we have a test case that should fail -> https://github.com/asyncapi/html-template/blob/master/test/all.is_expandable.test.js#L64-L66

Schema model always has `patternProperties` function, and it always returns `{}` unless there is something. This is why your fix works now, but to have a reliable test it should have  `t.context.doc.patternProperties = () => ({});` in the beforeEach function in between those lines https://github.com/asyncapi/html-template/blob/master/test/all.is_expandable.test.js#L5-L6

2020-10-15 12:10 UTC, gabrielclaudino commented
Thank you for the quick review. I changed the tests :)

2020-10-15 12:28 UTC, derberg approved these changes
Thanks a lot @gabrielclaudino 

LGTM

I only changed the title to something clearer for people looking later in the release notes

2020-10-15 12:28 UTC, merged

2020-10-15 12:30 UTC, gabrielclaudino commented
Okay!

2020-10-15 12:30 UTC, derberg commented
@all-contributors please add @gabrielclaudino for code

2020-10-15 12:35 UTC, derberg commented
@gabrielclaudino I would appreciate if you could share how did you learn about this project. Was it our blog post about Hacktoberfest, or Discord info. What resources were helpful, which one not. Would love to know your experience so we know how to make it better for next Hacktoberfest and where to advertise our involvement.

2020-10-19 20:18 UTC, gabrielclaudino commented
Sorry for the delay, I hadn't seen your question. I first heard about your project in the hacktoberfest Discord. I was browsing the project-sharing channel, and your post caught my attention. The issues spreadsheet help me a lot to pick a issue that suits my skills (more js related).

2020-10-19 20:24 UTC, derberg commented
@gabrielclaudino thanks for taking the time to answer 🙏